services:
  pg_vector:
    image: pgvector/pgvector:pg18
    container_name: pg_vector
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ai_chatbot
    networks:
      - base-network
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

networks:
  base-network:
    external: true

volumes:
  pgdata: